# Generated by oks_to_protocols.py from schema/confmodel/dunedaq.schema.xml -- DO NOT EDIT
# Protocols for conffwk DAL objects. Import for annotations only; they are not
# runtime_checkable.
from __future__ import annotations

from collections.abc import Sequence
from typing import Literal, Protocol


class DalObject(Protocol):
    @property
    def id(self) -> str: ...
    def className(self) -> str: ...
    def oksTypes(self) -> list[str]: ...
    def fullName(self) -> str: ...


class ActionPlan(DalObject, Protocol):
    """A set of steps for an application to carry out a command"""
    @property
    def execution_policy(self) -> Literal['modules-in-parallel', 'modules-in-series']: ...
    @property
    def command(self) -> FSMCommand: ...
    @property
    def steps(self) -> Sequence[DaqModulesGroup]: ...


class Application(DalObject, Protocol):
    """A software executable"""
    @property
    def application_name(self) -> str: ...
    @property
    def commandline_parameters(self) -> list[str]: ...
    @property
    def log_path(self) -> str: ...
    @property
    def application_environment(self) -> Sequence[VariableBase]: ...
    @property
    def runs_on(self) -> VirtualHost: ...
    @property
    def exposes_service(self) -> Sequence[Service]: ...
    @property
    def opmon_conf(self) -> OpMonConf: ...


class Connection(DalObject, Protocol):
    @property
    def data_type(self) -> str: ...
    @property
    def capacity(self) -> int: ...
    @property
    def send_timeout_ms(self) -> int: ...
    @property
    def recv_timeout_ms(self) -> int: ...


class ConnectionService(Application, Protocol):
    @property
    def threads(self) -> int: ...


class ConnectivityService(DalObject, Protocol):
    @property
    def interval_ms(self) -> int: ...
    @property
    def host(self) -> str: ...
    @property
    def service(self) -> Service: ...


class DaqApplication(Application, Protocol):
    @property
    def application_name(self) -> str: ...
    @property
    def modules(self) -> Sequence[DaqModule]: ...
    @property
    def action_plans(self) -> Sequence[ActionPlan]: ...


class DaqModule(DalObject, Protocol):
    """A plugin module for the app framework"""
    @property
    def inputs(self) -> Sequence[Connection]: ...
    @property
    def outputs(self) -> Sequence[Connection]: ...
    @property
    def used_host_components(self) -> Sequence[HostComponent]: ...


class DaqModulesGroup(DalObject, Protocol):
    """Represents a group of DAQ Modules that can run commands in parallel or in series as one of the steps of an ActionPlan."""
    @property
    def optional(self) -> bool: ...


class DaqModulesGroupById(DaqModulesGroup, Protocol):
    @property
    def modules(self) -> Sequence[DaqModule]: ...


class DaqModulesGroupByType(DaqModulesGroup, Protocol):
    @property
    def modules(self) -> list[str]: ...


class ExcludableEntity(DalObject, Protocol):
    """Base class for all ExcludableEntity objects. A ExcludableEntity is an object with an included/excluded state.
Derived classes must implement the compute_excluded_state() method to return the state."""
    pass


class DetDataReceiver(ExcludableEntity, Protocol):
    pass


class ExcludableEntitySet(ExcludableEntity, Protocol):
    """Base class for a collection of ExcludableEntity items. Derived classes must implement the contained_excludable_entities() method to return a vector of ExcludableEntity objects."""
    pass


class ExcludableEntitySetAND(ExcludableEntitySet, Protocol):
    """Abstract base class for a resource set that determines it's exclusion state by ANDing all its contained resources."""
    pass


class DetDataSender(ExcludableEntitySetAND, Protocol):
    @property
    def streams(self) -> Sequence[DetectorStream]: ...


class DetectorConfig(DalObject, Protocol):
    @property
    def tpg_channel_map(self) -> str: ...
    @property
    def clock_speed_hz(self) -> int: ...
    @property
    def op_env(self) -> str: ...
    @property
    def offline_data_stream(self) -> str: ...


class DetectorStream(ExcludableEntity, Protocol):
    @property
    def source_id(self) -> int: ...
    @property
    def geo_id(self) -> GeoId: ...


class DetectorToDaqConnection(ExcludableEntitySet, Protocol):
    pass


class ExcludableEntitySetOR(ExcludableEntitySet, Protocol):
    pass


class ExcludableEntityTree(DalObject, Protocol):
    @property
    def excluded(self) -> Sequence[ExcludableEntity]: ...


class FSMCommand(DalObject, Protocol):
    @property
    def cmd(self) -> str: ...
    @property
    def optional(self) -> bool: ...


class FSMaction(DalObject, Protocol):
    @property
    def name(self) -> str: ...
    @property
    def commands(self) -> list[str]: ...
    @property
    def parameters(self) -> Sequence[Variable]: ...


class FSMconfiguration(DalObject, Protocol):
    @property
    def states(self) -> list[str]: ...
    @property
    def initial_state(self) -> str: ...
    @property
    def transitions(self) -> Sequence[FSMtransition]: ...
    @property
    def command_sequences(self) -> Sequence[FSMsequence]: ...
    @property
    def pre_transitions(self) -> Sequence[FSMxTransition]: ...
    @property
    def post_transitions(self) -> Sequence[FSMxTransition]: ...
    @property
    def actions(self) -> Sequence[FSMaction]: ...


class FSMsequence(DalObject, Protocol):
    @property
    def name(self) -> list[str]: ...
    @property
    def sequence(self) -> Sequence[FSMCommand]: ...


class FSMtransition(DalObject, Protocol):
    @property
    def source(self) -> str: ...
    @property
    def dest(self) -> str: ...


class FSMxTransition(DalObject, Protocol):
    @property
    def transition(self) -> str: ...
    @property
    def order(self) -> list[str]: ...
    @property
    def mandatory(self) -> list[str]: ...


class GeoId(DalObject, Protocol):
    """The location of a stream, in detector geographical coordinates."""
    @property
    def detector_id(self) -> int: ...
    @property
    def crate_id(self) -> int: ...
    @property
    def slot_id(self) -> int: ...
    @property
    def stream_id(self) -> int: ...


class HostComponent(DalObject, Protocol):
    @property
    def numa_id(self) -> int: ...


class Jsonable(DalObject, Protocol):
    pass


class JsonableTest(Jsonable, Protocol):
    @property
    def this(self) -> int: ...
    @property
    def that(self) -> int: ...
    @property
    def other(self) -> JsonableTest | None: ...


class NetworkConnection(Connection, Protocol):
    @property
    def connection_type(self) -> Literal['kSendRecv', 'kPubSub']: ...
    @property
    def associated_service(self) -> Service: ...


class NetworkInterface(DalObject, Protocol):
    @property
    def mac_address(self) -> str: ...
    @property
    def ip_address(self) -> list[str]: ...
    @property
    def interface_name(self) -> str: ...
    @property
    def network_mask(self) -> str: ...
    @property
    def network_name(self) -> Literal['Control', 'Data']: ...


class NetworkDevice(HostComponent, NetworkInterface, Protocol):
    @property
    def pcie_addr(self) -> str: ...


class OpMonConf(DalObject, Protocol):
    @property
    def level(self) -> int: ...
    @property
    def interval_s(self) -> int: ...


class OpMonURI(DalObject, Protocol):
    @property
    def path(self) -> str: ...
    @property
    def type(self) -> Literal['stdout', 'file', 'stream']: ...


class PhysicalHost(DalObject, Protocol):
    @property
    def contains(self) -> Sequence[HostComponent]: ...


class HostCores(HostComponent, Protocol):
    @property
    def cpu_cores(self) -> list[int]: ...


class Queue(Connection, Protocol):
    @property
    def queue_type(self) -> Literal['kUnknown', 'kStdDeQueue', 'kFollySPSCQueue', 'kFollyMPMCQueue']: ...


class QueueWithSourceId(Queue, Protocol):
    @property
    def source_id(self) -> int: ...


class RCApplication(Application, Protocol):
    """An executable which allows users to control datataking"""
    @property
    def application_name(self) -> str: ...
    @property
    def fsm(self) -> FSMconfiguration: ...
    @property
    def broadcaster(self) -> RCBroadcaster | None: ...


class RCBroadcaster(DalObject, Protocol):
    @property
    def type(self) -> Literal['kafka', 'undefined']: ...
    @property
    def address(self) -> str: ...
    @property
    def publish_timeout(self) -> int: ...


class Segment(ExcludableEntitySet, Protocol):
    """Logical sub division of the configuration that can be included/excluded as a group"""
    @property
    def segments(self) -> Sequence[Segment]: ...
    @property
    def applications(self) -> Sequence[Application]: ...
    @property
    def controller(self) -> RCApplication: ...


class Service(DalObject, Protocol):
    @property
    def protocol(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def eth_device_name(self) -> str: ...
    @property
    def path(self) -> str: ...


class Session(ExcludableEntityTree, Protocol):
    @property
    def description(self) -> str: ...
    @property
    def data_request_timeout_ms(self) -> int: ...
    @property
    def data_rate_slowdown_factor(self) -> int: ...
    @property
    def rte_script(self) -> str: ...
    @property
    def controller_log_level(self) -> Literal['CRITICAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG']: ...
    @property
    def log_path(self) -> str: ...
    @property
    def connectivity_service(self) -> ConnectivityService | None: ...
    @property
    def environment(self) -> Sequence[VariableBase]: ...
    @property
    def segment(self) -> Segment: ...
    @property
    def infrastructure_applications(self) -> Sequence[Application]: ...
    @property
    def detector_configuration(self) -> DetectorConfig: ...
    @property
    def opmon_uri(self) -> OpMonURI: ...


class StorageDevice(HostComponent, Protocol):
    @property
    def storage(self) -> int: ...


class VariableBase(DalObject, Protocol):
    """This abstract class is used to describe a single variable (name:value pair) or a set of variables."""
    @property
    def description(self) -> str: ...


class Variable(VariableBase, Protocol):
    """A Variable associates a value with string name. It is used for process environment and database strings substitution."""
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...


class VariableSet(VariableBase, Protocol):
    """Set of variables or variable sets. Names and values of all nested variables are added to value of relationship using resource set."""
    @property
    def contains(self) -> Sequence[VariableBase]: ...


class VirtualHost(DalObject, Protocol):
    @property
    def uses(self) -> Sequence[HostComponent]: ...
    @property
    def runs_on(self) -> PhysicalHost: ...
