#!/usr/bin/env python3
"""Generate typing.Protocol classes from OKS schema files.

Usage: oks_to_protocols.py OUT.py SCHEMA.xml [SCHEMA.xml ...]

Type mapping follows conffwk/schema.py oks_types. Attributes without a value
read from the DB come back as their default ('' or 0), so they are not
Optional; single relationships with low-cc="zero" are.
"""

import keyword
import sys
import xml.etree.ElementTree as ET

# Mirrors conffwk/python/conffwk/schema.py oks_types
PY_TYPES = {
    "bool": "bool",
    **dict.fromkeys(["s8", "u8", "s16", "u16", "s32", "u32", "s64", "u64"], "int"),
    **dict.fromkeys(["float", "double"], "float"),
    **dict.fromkeys(["string", "uid", "class", "date", "time"], "str"),
}

HEADER = '''\
# Generated by oks_to_protocols.py from {sources} -- DO NOT EDIT
# Protocols for conffwk DAL objects. Import for annotations only; they are not
# runtime_checkable.
from __future__ import annotations

from collections.abc import Sequence
from typing import Literal, Protocol


class DalObject(Protocol):
    @property
    def id(self) -> str: ...
    def className(self) -> str: ...
    def oksTypes(self) -> list[str]: ...
    def fullName(self) -> str: ...
'''


def req(e: ET.Element, key: str) -> str:
    """Return a mandatory XML attribute, failing loudly on a malformed schema."""
    val = e.get(key)
    if val is None:
        raise ValueError(f"<{e.tag}> is missing required attribute {key!r}")
    return val


def attr_type(a: ET.Element) -> str:
    t = a.get("type", "")
    rng = a.get("range")
    if t == "enum" and rng:
        py = "Literal[" + ", ".join(repr(v) for v in rng.split(",")) + "]"
    else:
        py = PY_TYPES.get(t, "object")
    if a.get("is-multi-value") == "yes":
        py = f"list[{py}]"
    return py


def rel_type(r: ET.Element) -> str:
    cls = req(r, "class-type")
    if r.get("high-cc") == "many":
        return f"Sequence[{cls}]"
    if r.get("low-cc") == "zero":
        return f"{cls} | None"
    return cls


def prop(name: str, py: str) -> str:
    if keyword.iskeyword(name) or not name.isidentifier():
        return f"    # skipped {name!r}: not a valid identifier\n"
    return f"    @property\n    def {name}(self) -> {py}: ...\n"


def emit_class(c: ET.Element) -> str:
    supers = [req(s, "name") for s in c.findall("superclass")] or ["DalObject"]
    body = [prop(req(a, "name"), attr_type(a)) for a in c.findall("attribute")]
    body += [prop(req(r, "name"), rel_type(r)) for r in c.findall("relationship")]
    doc = c.get("description")
    head = f"class {req(c, 'name')}({', '.join(supers)}, Protocol):\n"
    if doc:
        head += f'    """{doc.strip()}"""\n'
    return head + ("".join(body) or "    pass\n")


def superclasses_first(classes: list[ET.Element]) -> list[ET.Element]:
    """Order classes so each base is defined before its subclasses."""
    by_name = {req(c, "name"): c for c in classes}
    done: dict[str, ET.Element] = {}

    def visit(c: ET.Element) -> None:
        for s in c.findall("superclass"):
            base = req(s, "name")
            if base in by_name and base not in done:
                visit(by_name[base])
        done[req(c, "name")] = c

    for c in classes:
        if req(c, "name") not in done:
            visit(c)
    return list(done.values())


def main(out: str, schemas: list[str]) -> None:
    classes = []
    for path in schemas:
        classes += ET.parse(path).getroot().findall("class")
    chunks = [HEADER.format(sources=", ".join(schemas))]
    chunks += [emit_class(c) for c in superclasses_first(classes)]
    with open(out, "w") as f:
        f.write("\n\n".join(chunks))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2:])
